# Generated by Django 6.0 on 2026-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='used_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
